### ISSUE TITLE
Open inspector in cards edit preview window opens it in main window instead

### ISSUE THREAD

**Issue by user202729** [hikaru-y/anki21-addon-ankiwebview-inspector#1]
![a](https://user-images.githubusercontent.com/25191436/80074383-409d3800-8573-11ea-8779-b3bf4d53c7a4.png)

When I right-click in the blue preview window and choose "inspect" option, the inspector (shown inside the red rectangle) is opened in the main window instead. (it cannot be interacted with because the cards edit dialog is modal)

**Comment by khonkhortisan** [comment]
Closing the card template dialog, expanding the inspection sidebar out to a window, then re-opening the card template dialog, the inspection window remains unable to be interacted with.

**Comment by andrewcrook** [comment]
I have the same issue. I planned on using this plugin to debug and add-on's screen.
