### ISSUE TITLE
Major rework

### ISSUE THREAD

**Issue by hikaru-y** [hikaru-y/anki21-addon-ankiwebview-inspector#12]
- [x] support Anki 2.1.50+
    - scoped PyQt enums
    - #6
- [x] display the inspector side-by-side or stacked vertically with the webview within a sub-window, such as the editor or card layout dialog
    - #1
    - #5
 - [x] zoom
 - [x] highlight the right-clicked element

**Comment by SamuelSwartzberg** [comment]
This is a great set of changes, and makes debugging my code-heavy card template so much easier. Thanks so much! ❤️
