### ISSUE TITLE
Inspector not working in editor?

### ISSUE THREAD

**Issue by ankidoc** [hikaru-y/anki21-addon-ankiwebview-inspector#19]
Hello,

I have the problem that when I'm in the editor, I can't open the inspector with right click. Is this intended or is this some kind of bug?
I'd really like to change some thinges with the css injector, but I need the attribute names for this.

Greetings from Germany

**Comment by hikaru-y** [comment]
Works for me. Try running Anki with only this add-on enabled and see if it works.

 Tested with the following environments: 
- OS: Win10, Lubuntu 22.04
- Anki version: 2.1.54, 2.1.55 Beta1 (Qt5, Qt6 builds)

Screenshot(Win10, 2.1.55 Beta1)
![2 1 55beta1_win10](https://user-images.githubusercontent.com/47855854/194758004-8de5130c-0397-4609-b7ea-80a55320ebd7.png)

**Comment by ankidoc** [comment]
Thanks for answering. I found out, that the Image occlusion add on was the problem. As long as it is activated, the option "inspect" does not appear in the editor anymore.

Working on MacOS BigSur latest
Anki 2.1.45
