### ISSUE TITLE
Is there a way to have it work in the Card Types window during styling?

### ISSUE THREAD

**Issue by Munzu** [hikaru-y/anki21-addon-ankiwebview-inspector#5]
Thanks so much for the add-on, it's super useful.

I'd like to also use the inspector while I style my cards. Is there a way to show the inspector in that window too? 
When i right-click on my card preview and select "Inspect", nothing happens.

**Comment by hikaru-y** [comment]
Hi @Munzu, sorry for the late reply.

I am currently working on that. See https://github.com/hikaru-y/anki21-addon-ankiwebview-inspector/issues/4#issuecomment-815075467 for more details.
